faiss_db:
  collection_nme: 'document_portal'  

embedding_model:
  google:  
    provider: 'google'
    model_name: 'models/text-embedding-004'
  huggingface:
    provider: 'huggingface'
    model_name: 'sentence-transformers/all-minilm-l6-v2'

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: 'deepseek-r1-distill-llama-70b'
    temperature: 0
    max_tokens: 2048

  openai:
    provider: "openai"
    model_name: 'gpt-4o-mini'
    temperature: 0  
    max_tokens: 2048

  google:
    provider: "google"
    model_name: 'gemini-2.0-flash'
    temperature: 0  
    max_tokens: 2048

